# Generated by Django 5.1.1 on 2024-09-11 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partie", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="room",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="room",
            name="name",
        ),
        migrations.AddField(
            model_name="room",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="room",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="play_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="room_name",
            field=models.CharField(default=1, max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="room",
            name="user_online",
            field=models.ManyToManyField(
                blank=True, related_name="online_in_groups", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="partie.room",
            ),
        ),
    ]
