# Generated by Django 5.1.1 on 2024-09-11 10:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partie', '0002_remove_room_created_at_remove_room_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='play_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
