# Generated by Django 5.1.1 on 2024-09-11 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partie', '0003_alter_room_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='user_online',
        ),
        migrations.AlterField(
            model_name='player',
            name='room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='partie.room'),
        ),
    ]
