# Generated by Django 5.1.1 on 2024-09-11 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partie', '0004_remove_room_user_online_alter_player_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='members',
            field=models.ManyToManyField(default=None, related_name='play_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
