# Generated by Django 5.1.1 on 2024-09-11 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partie', '0007_alter_player_color_alter_player_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='color',
            field=models.CharField(blank=True, choices=[('r', 'red'), ('y', 'yellow'), ('b', 'blue'), ('g', 'green')], max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_turn',
            field=models.BooleanField(default=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='partie.room')),
        ),
        migrations.AlterField(
            model_name='player',
            name='room',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='partie.room'),
        ),
    ]
