# Generated by Django 5.1.1 on 2024-09-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partie', '0008_alter_player_color_alter_player_is_turn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='is_turn',
            field=models.BooleanField(default=False),
        ),
    ]
