# Generated by Django 5.1.1 on 2024-09-11 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partie', '0009_alter_player_is_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='partie.room'),
        ),
    ]
