# Generated by Django 5.1.1 on 2024-09-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partie", "0010_alter_player_room"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="room",
        ),
        migrations.AddField(
            model_name="room",
            name="blue_taken",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="room",
            name="green_taken",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="room",
            name="red_taken",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="room",
            name="yellow_taken",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="room",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="rooms", to="partie.player"
            ),
        ),
    ]
